/// Countries offered in the Smart Invoice address, searchable in the picker.
const kCountries = <String>[
  'United Kingdom',
  'United States',
  'Bangladesh',
  'India',
  'Pakistan',
  'United Arab Emirates',
  'Saudi Arabia',
  'Qatar',
  'Kuwait',
  'Oman',
  'Bahrain',
  'Australia',
  'Canada',
  'Ireland',
  'Germany',
  'France',
  'Spain',
  'Italy',
  'Netherlands',
  'Belgium',
  'Portugal',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Poland',
  'Switzerland',
  'Austria',
  'Greece',
  'Turkey',
  'Egypt',
  'Nigeria',
  'Kenya',
  'South Africa',
  'Ghana',
  'Morocco',
  'China',
  'Japan',
  'South Korea',
  'Singapore',
  'Malaysia',
  'Indonesia',
  'Thailand',
  'Vietnam',
  'Philippines',
  'Sri Lanka',
  'Nepal',
  'New Zealand',
  'Brazil',
  'Mexico',
  'Argentina',
];
