import 'dart:io';

import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class DeviceCertificatePdf {
  static Future<File> build({
    required String deviceName,
    required String imei,
    required Map<String, String> fields,
    required double riskScore,
    required String riskDescription,
  }) async {
    final pdf = pw.Document();
    final riskPercent = (riskScore * 100).round();
    final riskLabel = riskPercent >= 80
        ? 'Low Risk'
        : riskPercent >= 50
        ? 'Medium Risk'
        : 'High Risk';
    final riskColor = riskPercent >= 80
        ? PdfColors.green
        : riskPercent >= 50
        ? PdfColors.orange
        : PdfColors.red;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          pw.Center(
            child: pw.Text(
              'DEVICE VERIFICATION CERTIFICATE',
              style: pw.TextStyle(
                fontSize: 20,
                fontWeight: pw.FontWeight.bold,
                letterSpacing: 1.2,
              ),
            ),
          ),
          pw.SizedBox(height: 6),
          pw.Center(
            child: pw.Text(
              'Generated by iMoScan',
              style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
            ),
          ),
          pw.SizedBox(height: 4),
          pw.Center(
            child: pw.Text(
              _formatDate(DateTime.now()),
              style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
            ),
          ),
          pw.SizedBox(height: 20),
          pw.Divider(color: PdfColors.grey400),
          pw.SizedBox(height: 16),
          pw.Container(
            padding: const pw.EdgeInsets.all(14),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  deviceName.isNotEmpty ? deviceName : 'Unknown Device',
                  style: pw.TextStyle(
                    fontSize: 16,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                if (imei.isNotEmpty) ...[
                  pw.SizedBox(height: 4),
                  pw.Text(
                    'IMEI: $imei',
                    style: const pw.TextStyle(fontSize: 11),
                  ),
                ],
              ],
            ),
          ),
          pw.SizedBox(height: 20),
          pw.Text(
            'Device Information',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 10),
          _buildFieldsTable(fields),
          pw.SizedBox(height: 24),
          pw.Text(
            'Risk Assessment',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 10),
          pw.Container(
            padding: const pw.EdgeInsets.all(14),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: riskColor, width: 1.5),
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      riskLabel,
                      style: pw.TextStyle(
                        fontSize: 14,
                        fontWeight: pw.FontWeight.bold,
                        color: riskColor,
                      ),
                    ),
                    pw.Text(
                      '$riskPercent%',
                      style: pw.TextStyle(
                        fontSize: 14,
                        fontWeight: pw.FontWeight.bold,
                        color: riskColor,
                      ),
                    ),
                  ],
                ),
                pw.SizedBox(height: 8),
                pw.Text(
                  riskDescription,
                  style: const pw.TextStyle(fontSize: 10),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 24),
          pw.Divider(color: PdfColors.grey400),
          pw.SizedBox(height: 8),
          pw.Text(
            'This certificate was generated automatically based on third-party provider data. '
            'It is provided for informational purposes only and does not constitute a guarantee.',
            style: pw.TextStyle(
              fontSize: 9,
              color: PdfColors.grey600,
              fontStyle: pw.FontStyle.italic,
            ),
          ),
        ],
      ),
    );

    final directory = await getTemporaryDirectory();
    final safeImei = imei.replaceAll(RegExp(r'[^a-zA-Z0-9]'), '');
    final fileName = safeImei.isNotEmpty
        ? 'device_certificate_$safeImei.pdf'
        : 'device_certificate_${DateTime.now().millisecondsSinceEpoch}.pdf';
    final file = File('${directory.path}/$fileName');
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  static pw.Widget _buildFieldsTable(Map<String, String> fields) {
    final entries = fields.entries.toList();
    final rows = <List<String>>[];

    for (var i = 0; i < entries.length; i += 2) {
      final left = entries[i];
      final right = i + 1 < entries.length ? entries[i + 1] : null;
      if (right != null) {
        rows.add([left.key, left.value, right.key, right.value]);
      } else {
        rows.add([left.key, left.value, '', '']);
      }
    }

    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300),
      columnWidths: {
        0: const pw.FlexColumnWidth(1.2),
        1: const pw.FlexColumnWidth(1.5),
        2: const pw.FlexColumnWidth(1.2),
        3: const pw.FlexColumnWidth(1.5),
      },
      children: rows.map((row) {
        return pw.TableRow(
          children: row.asMap().entries.map((entry) {
            final isLabel = entry.key == 0 || entry.key == 2;
            return pw.Padding(
              padding: const pw.EdgeInsets.symmetric(
                horizontal: 8,
                vertical: 6,
              ),
              child: pw.Text(
                entry.value,
                style: pw.TextStyle(
                  fontSize: 10,
                  fontWeight: isLabel
                      ? pw.FontWeight.bold
                      : pw.FontWeight.normal,
                  color: isLabel ? PdfColors.grey700 : PdfColors.black,
                ),
              ),
            );
          }).toList(),
        );
      }).toList(),
    );
  }

  static String _formatDate(DateTime value) {
    final month = value.month.toString().padLeft(2, '0');
    final day = value.day.toString().padLeft(2, '0');
    final hour = value.hour.toString().padLeft(2, '0');
    final minute = value.minute.toString().padLeft(2, '0');
    return '${value.year}-$month-$day $hour:$minute';
  }
}
